#define AIR_STRIKE_IDC_DISPLAY                  910000
#define AIR_STRIKE_IDC_HEADER_BACKGROUND        910001
#define AIR_STRIKE_IDC_BODY_BACKGROUND          910002
#define AIR_STRIKE_IDC_CANCEL_BUTTON            910003
#define AIR_STRIKE_IDC_OK_BUTTON                910004
#define AIR_STRIKE_IDC_PLANE_INFO_FRAME         910005
#define AIR_STRIKE_IDC_PLANE_TYPE_HEADER        910006
#define AIR_STRIKE_IDC_PLANE_TYPE_COMBO         910007
#define AIR_STRIKE_IDC_NUMBER_OF_PLANES_HEADER  910008
#define AIR_STRIKE_IDC_NUMBER_OF_PLANES_SLIDER  910009
#define AIR_STRIKE_IDC_NUMBER_OF_PLANES_READOUT 910010
#define AIR_STRIKE_IDC_FORMATION_HEADER         910011
#define AIR_STRIKE_IDC_FORMATION_COMBO          910012
#define AIR_STRIKE_IDC_BOMB_INFO_FRAME          910013
#define AIR_STRIKE_IDC_BOMB_TYPE_HEADER         910014
#define AIR_STRIKE_IDC_BOMB_TYPE_COMBO          910015
#define AIR_STRIKE_IDC_NUMBER_OF_BOMBS_HEADER   910016
#define AIR_STRIKE_IDC_NUMBER_OF_BOMBS_SLIDER   910017
#define AIR_STRIKE_IDC_NUMBER_OF_BOMBS_READOUT  910018
#define AIR_STRIKE_IDC_BOMBS_SPREAD_HEADER      910019
#define AIR_STRIKE_IDC_BOMBS_SPREAD_SLIDER      910020
#define AIR_STRIKE_IDC_BOMBS_SPREAD_READOUT     910021
#define AIR_STRIKE_IDC_FLIGHT_INFO_FRAME        910022
#define AIR_STRIKE_IDC_FLIGHT_SPEED_HEADER      910023
#define AIR_STRIKE_IDC_FLIGHT_SPEED_SLIDER      910024
#define AIR_STRIKE_IDC_FLIGHT_SPEED_READOUT     910025
#define AIR_STRIKE_IDC_FLIGHT_ALTITUDE_HEADER   910026
#define AIR_STRIKE_IDC_FLIGHT_ALTITUDE_SLIDER   910027
#define AIR_STRIKE_IDC_FLIGHT_ALTITUDE_READOUT  910028
#define AIR_STRIKE_IDC_SPAWN_INFO_FRAME         910029
#define AIR_STRIKE_IDC_SPAWN_BEARING_HEADER     910030
#define AIR_STRIKE_IDC_SPAWN_BEARING_SLIDER     910031
#define AIR_STRIKE_IDC_SPAWN_BEARING_READOUT    910032
#define AIR_STRIKE_IDC_SPAWN_DISTANCE_HEADER    910033
#define AIR_STRIKE_IDC_SPAWN_DISTANCE_SLIDER    910034
#define AIR_STRIKE_IDC_SPAWN_DISTANCE_READOUT   910035
#define AIR_STRIKE_IDC_DESPAWN_INFO_FRAME       910036
#define AIR_STRIKE_IDC_DESPAWN_BEARING_HEADER   910037
#define AIR_STRIKE_IDC_DESPAWN_BEARING_SLIDER   910038
#define AIR_STRIKE_IDC_DESPAWN_BEARING_READOUT  910039
#define AIR_STRIKE_IDC_DESPAWN_DISTANCE_HEADER  910040
#define AIR_STRIKE_IDC_DESPAWN_DISTANCE_SLIDER  910041
#define AIR_STRIKE_IDC_DESPAWN_DISTANCE_READOUT 910042

#define AIR_STRIKE_IDC_INPUTS [AIR_STRIKE_IDC_PLANE_TYPE_COMBO, AIR_STRIKE_IDC_NUMBER_OF_PLANES_SLIDER, AIR_STRIKE_IDC_FORMATION_COMBO, AIR_STRIKE_IDC_BOMB_TYPE_COMBO, AIR_STRIKE_IDC_NUMBER_OF_BOMBS_SLIDER, AIR_STRIKE_IDC_BOMBS_SPREAD_SLIDER, AIR_STRIKE_IDC_FLIGHT_ALTITUDE_SLIDER, AIR_STRIKE_IDC_FLIGHT_SPEED_SLIDER, AIR_STRIKE_IDC_SPAWN_BEARING_SLIDER, AIR_STRIKE_IDC_SPAWN_DISTANCE_SLIDER, AIR_STRIKE_IDC_DESPAWN_BEARING_SLIDER, AIR_STRIKE_IDC_DESPAWN_DISTANCE_SLIDER]
#define AIR_STRIKE_IDC_PLANE_CHANGED [AIR_STRIKE_IDC_PLANE_TYPE_COMBO, AIR_STRIKE_IDC_BOMB_TYPE_COMBO, AIR_STRIKE_IDC_NUMBER_OF_BOMBS_SLIDER, AIR_STRIKE_IDC_NUMBER_OF_BOMBS_READOUT, AIR_STRIKE_IDC_FLIGHT_SPEED_SLIDER, AIR_STRIKE_IDC_FLIGHT_SPEED_READOUT]
#define AIR_STRIKE_IDC_BOMB_CHANGED [AIR_STRIKE_IDC_PLANE_TYPE_COMBO, AIR_STRIKE_IDC_BOMB_TYPE_COMBO, AIR_STRIKE_IDC_NUMBER_OF_BOMBS_SLIDER, AIR_STRIKE_IDC_NUMBER_OF_BOMBS_READOUT]

#define AIR_STRIKE_NUMBER_OF_PLANES_RANGE   {1 , 10}
#define AIR_STRIKE_NUMBER_OF_PLANES_STEP    1
#define AIR_STRIKE_NUMBER_OF_PLANES_DEFAULT 1
#define AIR_STRIKE_NUMBER_OF_BOMBS_RANGE    {0 , 0}
#define AIR_STRIKE_NUMBER_OF_BOMBS_STEP     1
#define AIR_STRIKE_NUMBER_OF_BOMBS_DEFAULT  0
#define AIR_STRIKE_BOMBS_SPREAD_RANGE       {10 , 500}
#define AIR_STRIKE_BOMBS_SPREAD_STEP        1
#define AIR_STRIKE_BOMBS_SPREAD_DEFAULT     50
#define AIR_STRIKE_FLIGHT_SPEED_RANGE       {0 , 0}
#define AIR_STRIKE_FLIGHT_SPEED_STEP        1
#define AIR_STRIKE_FLIGHT_SPEED_DEFAULT     0
#define AIR_STRIKE_FLIGHT_ALTITUDE_RANGE    {50 , 1000}
#define AIR_STRIKE_FLIGHT_ALTITUDE_STEP     1
#define AIR_STRIKE_FLIGHT_ALTITUDE_DEFAULT  100
#define AIR_STRIKE_SPAWN_BEARING_RANGE      {0 , 359}
#define AIR_STRIKE_SPAWN_BEARING_STEP       1
#define AIR_STRIKE_SPAWN_BEARING_DEFAULT    180
#define AIR_STRIKE_SPAWN_DISTANCE_RANGE     {1000 , 10000}
#define AIR_STRIKE_SPAWN_DISTANCE_STEP      1
#define AIR_STRIKE_SPAWN_DISTANCE_DEFAULT   2000
#define AIR_STRIKE_DESPAWN_BEARING_RANGE    {0 , 359}
#define AIR_STRIKE_DESPAWN_BEARING_STEP     1
#define AIR_STRIKE_DESPAWN_BEARING_DEFAULT  0
#define AIR_STRIKE_DESPAWN_DISTANCE_RANGE   {1000 , 10000}
#define AIR_STRIKE_DESPAWN_DISTANCE_STEP    1
#define AIR_STRIKE_DESPAWN_DISTANCE_DEFAULT 2000
