class RscDisplayAttributes;
class RscFrame;
class RscPicture;
class IGUIBack;
class RscButton;
class RscButtonMenu;
class RscButtonMenuCancel;
class RscButtonMenuOK;
class RscCheckbox;
class RscCombo;
class RscControlsGroup;
class RscListBox;
class RscSlider;
class RscText;
class RscEdit;
class RscXSliderH;

#include "CfgDisplayMainMacros.hpp"
#include "CfgDisplayModuleArtilleryStrike.hpp"
#include "CfgDisplayModuleAirStrike.hpp"
